export const ACADEMY_LIST_REQUEST = "ACADEMY_LIST_REQUEST";
export const ACADEMY_LIST_SUCCESS = "ACADEMY_LIST_SUCCESS";
export const ACADEMY_LIST_FAIL = "ACADEMY_LIST_FAIL";

export const ACADEMY_LIST_SEARCH_REQUEST = "ACADEMY_LIST_SEARCH_REQUEST";
export const ACADEMY_LIST_SEARCH_SUCCESS = "ACADEMY_LIST_SEARCH_SUCCESS";
export const ACADEMY_LIST_SEARCH_FAIL = "ACADEMY_LIST_SEARCH_FAIL";

export const ACADEMY_LIST_SEARCH_CATEGORY_REQUEST = "ACADEMY_LIST_SEARCH_CATEGORY_REQUEST";
export const ACADEMY_LIST_SEARCH_CATEGORY_SUCCESS = "ACADEMY_LIST_SEARCH_CATEGORY_SUCCESS";
export const ACADEMY_LIST_SEARCH_CATEGORY_FAIL = "ACADEMY_LIST_SEARCH_CATEGORY_FAIL";

export const ACADEMY_CATEGORY_LIST_REQUEST = "ACADEMY_CATEGORY_LIST_REQUEST";
export const ACADEMY_CATEGORY_LIST_SUCCESS = "ACADEMY_CATEGORY_LIST_SUCCESS";
export const ACADEMY_CATEGORY_LIST_FAIL = "ACADEMY_CATEGORY_LIST_FAIL";

export const ACADEMY_LIST_RELATED_REQUEST = "ACADEMY_LIST_RELATED_REQUEST";
export const ACADEMY_LIST_RELATED_SUCCESS = "ACADEMY_LIST_RELATED_SUCCESS";
export const ACADEMY_LIST_RELATED_FAIL = "ACADEMY_LIST_RELATED_FAIL";

export const ACADEMY_DETAILS_REQUEST = "ACADEMY_DETAILS_REQUEST";
export const ACADEMY_DETAILS_SUCCESS = "ACADEMY_DETAILS_SUCCESS";
export const ACADEMY_DETAILS_FAIL = "ACADEMY_DETAILS_FAIL";

export const ACADEMY_WATCHLIST_CREATE_REQUEST = "ACADEMY_WATCHLIST_CREATE_REQUEST";
export const ACADEMY_WATCHLIST_CREATE_SUCCESS = "ACADEMY_WATCHLIST_CREATE_SUCCESS";
export const ACADEMY_WATCHLIST_CREATE_FAIL = "ACADEMY_WATCHLIST_CREATE_FAIL";
export const ACADEMY_WATCHLIST_CREATE_RESET = "ACADEMY_WATCHLIST_CREATE_RESET";

export const ACADEMY_REVIEW_CREATE_REQUEST = 'ACADEMY_REVIEW_CREATE_REQUEST';
export const ACADEMY_REVIEW_CREATE_SUCCESS = 'ACADEMY_REVIEW_CREATE_SUCCESS';
export const ACADEMY_REVIEW_CREATE_FAIL = 'ACADEMY_REVIEW_CREATE_FAIL';
export const ACADEMY_REVIEW_CREATE_RESET = 'ACADEMY_REVIEW_CREATE_RESET';

export const ACADEMY_REVIEW_GET_REQUEST = 'ACADEMY_REVIEW_GET_REQUEST';
export const ACADEMY_REVIEW_GET_SUCCESS = 'ACADEMY_REVIEW_GET_SUCCESS';
export const ACADEMY_REVIEW_GET_FAIL = 'ACADEMY_REVIEW_GET_FAIL';

export const ACADEMY_OUTLINE_REQUEST = "ACADEMY_OUTLINE_REQUEST";
export const ACADEMY_OUTLINE_SUCCESS = "ACADEMY_OUTLINE_SUCCESS";
export const ACADEMY_OUTLINE_FAIL = "ACADEMY_OUTLINE_FAIL";

export const ACADEMY_OUTLINE_DETAIL_REQUEST = "ACADEMY_OUTLINE_DETAIL_REQUEST";
export const ACADEMY_OUTLINE_DETAIL_SUCCESS = "ACADEMY_OUTLINE_DETAIL_SUCCESS";
export const ACADEMY_OUTLINE_DETAIL_FAIL = "ACADEMY_OUTLINE_DETAIL_FAIL";
