export const CART_ADD_ITEM = "CART_ADD_ITEM";
export const CART_REMOVE_ITEM = "CART_REMOVE_ITEM";

export const CART_REGISTER_ITEMS_REQUEST = "CART_REGISTER_ITEMS_REQUEST";
export const CART_REGISTER_ITEMS_SUCCESS = "CART_REGISTER_ITEMS_SUCCESS";
export const CART_REGISTER_ITEMS_FAIL = "CART_REGISTER_ITEMS_FAIL";
export const CART_REGISTER_ITEMS_RESET = "CART_REGISTER_ITEMS_RESET";

export const CART_EMPTY = "CART_EMPTY";