const data = {
    accademys: [
        {"academy_id":3,"academy_category_id":2,"academy_name":"Lập trình VueJS","avatar":"https://i.ibb.co/85Ssw1y/1.png","description_short":"Đây là mô tả ngắn","description_detail":"Đây là mô tả chi tiết","price":0,"status":null,"teacher_id":1,"promotion":null,"view":8,"rate":4.1,"is_delete":0,"created_at":"2021-06-29T08:51:55.000Z","updated_at":null},
        {"academy_id":10,"academy_category_id":2,"academy_name":"Lập trình VueJS","avatar":"https://i.ibb.co/85Ssw1y/1.png","description_short":"Đây là mô tả ngắn","description_detail":"Đây là mô tả chi tiết","price":0,"status":null,"teacher_id":1,"promotion":null,"view":8,"rate":4.1,"is_delete":0,"created_at":"2021-06-29T08:51:55.000Z","updated_at":null},
        {"academy_id":5,"academy_category_id":3,"academy_name":"Lập trình React Native","avatar":"https://i.ibb.co/ch8dHPv/4.jpg","description_short":"Đây là mô tả ngắn","description_detail":"Đây là mô tả chi tiết","price":0,"status":null,"teacher_id":1,"promotion":null,"view":4,"rate":3.8,"is_delete":0,"created_at":"2021-06-29T08:51:55.000Z","updated_at":null},
        {"academy_id":12,"academy_category_id":3,"academy_name":"Lập trình React Native","avatar":"https://i.ibb.co/ch8dHPv/4.jpg","description_short":"Đây là mô tả ngắn","description_detail":"Đây là mô tả chi tiết","price":0,"status":null,"teacher_id":1,"promotion":null,"view":4,"rate":3.8,"is_delete":0,"created_at":"2021-06-29T08:51:55.000Z","updated_at":null},
        {"academy_id":2,"academy_category_id":2,"academy_name":"Lập trình Angular","avatar":"https://i.ibb.co/kJZsvHM/8.jpg","description_short":"Đây là mô tả ngắn","description_detail":"Đây là mô tả chi tiết","price":0,"status":null,"teacher_id":1,"promotion":null,"view":3,"rate":4.3,"is_delete":0,"created_at":"2021-06-29T08:51:55.000Z","updated_at":null},
        {"academy_id":9,"academy_category_id":2,"academy_name":"Lập trình Angular","avatar":"https://i.ibb.co/kJZsvHM/8.jpg","description_short":"Đây là mô tả ngắn","description_detail":"Đây là mô tả chi tiết","price":0,"status":null,"teacher_id":1,"promotion":null,"view":3,"rate":4.3,"is_delete":0,"created_at":"2021-06-29T08:51:55.000Z","updated_at":null},
        {"academy_id":1,"academy_category_id":2,"academy_name":"Lập trình ReactJS","avatar":"https://i.ibb.co/ch8dHPv/4.jpg","description_short":"Đây là mô tả ngắn","description_detail":"Đây là mô tả chi tiết","price":0,"status":null,"teacher_id":1,"promotion":null,"view":2,"rate":5,"is_delete":0,"created_at":"2021-06-29T08:50:51.000Z","updated_at":null},
        {"academy_id":8,"academy_category_id":2,"academy_name":"Lập trình ReactJS","avatar":"https://i.ibb.co/ch8dHPv/4.jpg","description_short":"Đây là mô tả ngắn","description_detail":"Đây là mô tả chi tiết","price":0,"status":null,"teacher_id":1,"promotion":null,"view":2,"rate":5,"is_delete":0,"created_at":"2021-06-29T08:50:51.000Z","updated_at":null},
        {"academy_id":4,"academy_category_id":3,"academy_name":"Lập trình Android studio","avatar":"https://i.ibb.co/5Fx9ZQ9/11.jpg","description_short":"Đây là mô tả ngắn","description_detail":"Đây là mô tả chi tiết","price":0,"status":null,"teacher_id":1,"promotion":null,"view":1,"rate":3.2,"is_delete":0,"created_at":"2021-06-29T08:51:55.000Z","updated_at":null},
        {"academy_id":11,"academy_category_id":3,"academy_name":"Lập trình Android studio","avatar":"https://i.ibb.co/5Fx9ZQ9/11.jpg","description_short":"Đây là mô tả ngắn","description_detail":"Đây là mô tả chi tiết","price":0,"status":null,"teacher_id":1,"promotion":null,"view":1,"rate":3.2,"is_delete":0,"created_at":"2021-06-29T08:51:55.000Z","updated_at":null}
    ]
};

export default data;

// const data = {
//     accademys: [
//         {academy_id:3,academy_category_id:2,academy_name:"Lập trình VueJS",avatar:"https://i.ibb.co/85Ssw1y/1.png",description_short:"Đây là mô tả ngắn",description_detail:"Đây là mô tả chi tiết",price:0,"status":null,teacher_id:1,promotion:null,view:8,rate:4.1,is_delete:0,created_at:"2021-06-29T08:51:55.000Z",updated_at:null},
//         {academy_id:10,academy_category_id:2,academy_name:"Lập trình VueJS",avatar:"https://i.ibb.co/85Ssw1y/1.png",description_short:"Đây là mô tả ngắn",description_detail:"Đây là mô tả chi tiết",price:0,"status":null,teacher_id:1,promotion:null,view:8,rate:4.1,is_delete:0,created_at:"2021-06-29T08:51:55.000Z",updated_at:null},
//         {academy_id:5,academy_category_id:3,academy_name:"Lập trình React Native",avatar:"https://i.ibb.co/ch8dHPv/4.jpg",description_short:"Đây là mô tả ngắn",description_detail:"Đây là mô tả chi tiết",price:0,"status":null,teacher_id:1,promotion:null,view:4,rate:3.8,is_delete:0,created_at:"2021-06-29T08:51:55.000Z",updated_at:null},
//         {academy_id:12,academy_category_id:3,academy_name:"Lập trình React Native",avatar:"https://i.ibb.co/ch8dHPv/4.jpg",description_short:"Đây là mô tả ngắn",description_detail:"Đây là mô tả chi tiết",price:0,"status":null,teacher_id:1,promotion:null,view:4,rate:3.8,is_delete:0,created_at:"2021-06-29T08:51:55.000Z",updated_at:null},
//         {academy_id:2,academy_category_id:2,academy_name:"Lập trình Angular",avatar:"https://i.ibb.co/kJZsvHM/8.jpg",description_short:"Đây là mô tả ngắn",description_detail:"Đây là mô tả chi tiết",price:0,"status":null,teacher_id:1,promotion:null,view:3,rate:4.3,is_delete:0,created_at:"2021-06-29T08:51:55.000Z",updated_at:null},
//         {academy_id:9,academy_category_id:2,academy_name:"Lập trình Angular",avatar:"https://i.ibb.co/kJZsvHM/8.jpg",description_short:"Đây là mô tả ngắn",description_detail:"Đây là mô tả chi tiết",price:0,"status":null,teacher_id:1,promotion:null,view:3,rate:4.3,is_delete:0,created_at:"2021-06-29T08:51:55.000Z",updated_at:null},
//         {academy_id:1,academy_category_id:2,academy_name:"Lập trình ReactJS",avatar:"https://i.ibb.co/ch8dHPv/4.jpg",description_short:"Đây là mô tả ngắn",description_detail:"Đây là mô tả chi tiết",price:0,"status":null,teacher_id:1,promotion:null,view:2,rate:5,is_delete:0,created_at:"2021-06-29T08:50:51.000Z",updated_at:null},
//         {academy_id:8,academy_category_id:2,academy_name:"Lập trình ReactJS",avatar:"https://i.ibb.co/ch8dHPv/4.jpg",description_short:"Đây là mô tả ngắn",description_detail:"Đây là mô tả chi tiết",price:0,"status":null,teacher_id:1,promotion:null,view:2,rate:5,is_delete:0,created_at:"2021-06-29T08:50:51.000Z",updated_at:null},
//         {academy_id:4,academy_category_id:3,academy_name:"Lập trình Android studio",avatar:"https://i.ibb.co/5Fx9ZQ9/11.jpg",description_short:"Đây là mô tả ngắn",description_detail:"Đây là mô tả chi tiết",price:0,"status":null,teacher_id:1,promotion:null,view:1,rate:3.2,is_delete:0,created_at:"2021-06-29T08:51:55.000Z",updated_at:null},
//         {academy_id:11,academy_category_id:3,academy_name:"Lập trình Android studio",avatar:"https://i.ibb.co/5Fx9ZQ9/11.jpg",description_short:"Đây là mô tả ngắn",description_detail:"Đây là mô tả chi tiết",price:0,"status":null,teacher_id:1,promotion:null,view:1,rate:3.2,is_delete:0,created_at:"2021-06-29T08:51:55.000Z",updated_at:null}
//     ]
// };

// export default data;

// const data = {
//     accademys: [
//         {academy_id:"3",academy_category_id:2,academy_name:"Lập trình VueJS",avatar:"https://i.ibb.co/85Ssw1y/1.png",description_short:"Đây là mô tả ngắn",description_detail:"Đây là mô tả chi tiết",price:0,"status":null,teacher_id:1,promotion:null,view:8,rate:4.1,is_delete:0,created_at:"2021-06-29T08:51:55.000Z",updated_at:null},
//         {academy_id:"10",academy_category_id:2,academy_name:"Lập trình VueJS",avatar:"https://i.ibb.co/85Ssw1y/1.png",description_short:"Đây là mô tả ngắn",description_detail:"Đây là mô tả chi tiết",price:0,"status":null,teacher_id:1,promotion:null,view:8,rate:4.1,is_delete:0,created_at:"2021-06-29T08:51:55.000Z",updated_at:null},
//         {academy_id:"5",academy_category_id:3,academy_name:"Lập trình React Native",avatar:"https://i.ibb.co/ch8dHPv/4.jpg",description_short:"Đây là mô tả ngắn",description_detail:"Đây là mô tả chi tiết",price:0,"status":null,teacher_id:1,promotion:null,view:4,rate:3.8,is_delete:0,created_at:"2021-06-29T08:51:55.000Z",updated_at:null},
//         {academy_id:"12",academy_category_id:3,academy_name:"Lập trình React Native",avatar:"https://i.ibb.co/ch8dHPv/4.jpg",description_short:"Đây là mô tả ngắn",description_detail:"Đây là mô tả chi tiết",price:0,"status":null,teacher_id:1,promotion:null,view:4,rate:3.8,is_delete:0,created_at:"2021-06-29T08:51:55.000Z",updated_at:null},
//         {academy_id:"2",academy_category_id:2,academy_name:"Lập trình Angular",avatar:"https://i.ibb.co/kJZsvHM/8.jpg",description_short:"Đây là mô tả ngắn",description_detail:"Đây là mô tả chi tiết",price:0,"status":null,teacher_id:1,promotion:null,view:3,rate:4.3,is_delete:0,created_at:"2021-06-29T08:51:55.000Z",updated_at:null},
//         {academy_id:"9",academy_category_id:2,academy_name:"Lập trình Angular",avatar:"https://i.ibb.co/kJZsvHM/8.jpg",description_short:"Đây là mô tả ngắn",description_detail:"Đây là mô tả chi tiết",price:0,"status":null,teacher_id:1,promotion:null,view:3,rate:4.3,is_delete:0,created_at:"2021-06-29T08:51:55.000Z",updated_at:null},
//         {academy_id:"1",academy_category_id:2,academy_name:"Lập trình ReactJS",avatar:"https://i.ibb.co/ch8dHPv/4.jpg",description_short:"Đây là mô tả ngắn",description_detail:"Đây là mô tả chi tiết",price:0,"status":null,teacher_id:1,promotion:null,view:2,rate:5,is_delete:0,created_at:"2021-06-29T08:50:51.000Z",updated_at:null},
//         {academy_id:"8",academy_category_id:2,academy_name:"Lập trình ReactJS",avatar:"https://i.ibb.co/ch8dHPv/4.jpg",description_short:"Đây là mô tả ngắn",description_detail:"Đây là mô tả chi tiết",price:0,"status":null,teacher_id:1,promotion:null,view:2,rate:5,is_delete:0,created_at:"2021-06-29T08:50:51.000Z",updated_at:null},
//         {academy_id:"4",academy_category_id:3,academy_name:"Lập trình Android studio",avatar:"https://i.ibb.co/5Fx9ZQ9/11.jpg",description_short:"Đây là mô tả ngắn",description_detail:"Đây là mô tả chi tiết",price:0,"status":null,teacher_id:1,promotion:null,view:1,rate:3.2,is_delete:0,created_at:"2021-06-29T08:51:55.000Z",updated_at:null},
//         {academy_id:"11",academy_category_id:3,academy_name:"Lập trình Android studio",avatar:"https://i.ibb.co/5Fx9ZQ9/11.jpg",description_short:"Đây là mô tả ngắn",description_detail:"Đây là mô tả chi tiết",price:0,"status":null,teacher_id:1,promotion:null,view:1,rate:3.2,is_delete:0,created_at:"2021-06-29T08:51:55.000Z",updated_at:null}
//     ]
// };

// export default data;